### ISSUE TITLE
Add support for Java 8 Stream

### ISSUE THREAD

**Issue by charlesxucheng** [jsurfer/JsonSurfer#17]
Thanks for your great work. Is it possible to add in support for Java 8 Stream? e.g. return a stream of objects so that the stream can emit new elements as soon as they arrive from the Json input stream.

**Comment by wanglingsong** [comment]
That's good idea! I would say yes. Are you interested in contributing and implementing this feature?

**Comment by charlesxucheng** [comment]
I can try, but not very sure how it can be done yet.

**Comment by wanglingsong** [comment]
OK, let me do the study first.

**Comment by charlesxucheng** [comment]
Another question is if I have an URL (a REST service) that will return me a JSON response, how can I make use of JsonSurfer to process the JSON on the fly? 

I see that the surf method takes a Reader parameter, but I am not sure how to get a Reader object from the response in the client code. I am using Spring MVC for the REST WS, and am trying JsonSurfer to consume the result returned by the WS.

**Comment by wanglingsong** [comment]
Can you get a InputStream from the JSON response? If so, you can use InputStreamReader to read from the InputStream.

**Comment by wanglingsong** [comment]
Sorry.I think Stream API is not feasible for JsonSurfer because JsonSurfer is designed to dispatch data by triggering event which is push-based. However, Stream is pull-based API. It asks for data to process. Assuming that you want to do some transformation on the data emitted from JsonSurfer. There are some great reactive programming library available like [RxJava](https://github.com/ReactiveX/RxJava) or [simple-react](https://github.com/aol/simple-react)

**Comment by charlesxucheng** [comment]
Ok thanks!

**Comment by mohamed3aly** [comment]
Try RxSON: <https://github.com/rxson/rxson>
It utilizes the JsonPath wit RxJava to read JSON streamed chunks from the response as soon as they arrive, and parse them to java objects before the reponse complete.

Example:
```
String serviceURL = "https://think.cs.vt.edu/corgis/datasets/json/airlines/airlines.json";
   HttpRequest req = HttpRequest.newBuilder(URI.create(serviceURL)).GET().build();
   RxSON rxson = new RxSON.Builder().build();

   String jsonPath = "$[*].Airport.Name";
   Flowable<String> airportStream = rxson.create(String.class, req, jsonPath);
   airportStream
       .doOnNext(it -> System.out.println("Received new item: " + it))
       //Just for test
       .toList()
       .blockingGet();
```
