### ISSUE TITLE
Parent POM is missing from maven repository for 1.3 Release

### ISSUE THREAD

**Issue by paul-amperity** [jsurfer/JsonSurfer#22]
I'm getting the following error attempting to depend on jsurfer-core 1.3 and jsurfer-jackson 1.3

`Could not find artifact com.github.jsurfer:jsurfer:pom:1.3 in central (https://repo1.maven.org/maven2/)`

**Comment by wanglingsong** [comment]
I missed deploying the parent module. Will try to fix it soon.

**Comment by wanglingsong** [comment]
Hi @paul-amperity,
A new version 1.3.1 is released instead. It may take a while for the central maven repo to populate it. Before it's ready, you can clone the source and build it your self. Thanks so much for the reminder.
