### ISSUE TITLE
Android compatibility issue

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [jsurfer/JsonSurfer#25]
JsonSurfer works in my Note 4 running Android 6 but in my Nexus 4 device which is
running on Android 4.2 it crashes on the second line:

JsonSurfer surfer = JsonSurferGson.INSTANCE;
> Object statementIDObj = surfer.collectOne(myResponse, "$.results[0].statement_id");

producing the error: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets .

Now I know that Standard Charsets were introduced in KitKat but I wanted to ask if there
is a workaround for this. Thank you

**Comment by wanglingsong** [comment]
JsonSurfer doesn't import StandardCharsets class in its source. Could you check again? Maybe it is introduced by your soruce.

**Comment by Theofilos-Chamalis** [comment]
I tried also the JsonPath library and it seems that this happens also there, so I believe it is something that JsonPath uses internally.

**Comment by wanglingsong** [comment]
Could you provide the whole stacktrace?
