### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by oleg-smith** [jsurfer/JsonSurfer#26]
JsonSurf is currently event-driven, let's consider use case of processing big json with JsonPath expression:

1) it will not load entire json in memory
2) it will load all results in memory (in a collection) in event listener, in order to return it to caller.

The proposal is to provide an iterator, so that client code can interact with parser in pull manner, getting events one by one.

**Comment by wanglingsong** [comment]
There is an API to collect value into a collection for JsonSurfer. You can create an iterator from it.
https://github.com/jsurfer/JsonSurfer#colllect-every-matched-value-in-a-collection

**Comment by oleg-smith** [comment]
I don't need just iterator, I need iterator that is tightly coupled with parser.

Say, you have 1 million elements in json, so you need to create a collection out of this 1 million records in memory instead of having iterator, that allows to to parse and process elements one by one.

**Comment by wanglingsong** [comment]
OK, I got your idea. In fact, it is not the first proposal for java8-like stream support. But so far I have no clue how to implement it. Any suggestion?

**Comment by oleg-smith** [comment]
I guess you have somewhere event loop while - I'd break this loop and added iterator, where hasNext() method would do the same as the loop body until it detects a match with provided JsonPath and stores it in a field inside the iterator.

And next() method would just return this value.

**Comment by wanglingsong** [comment]
Hi @oleg-smith , I just implemented the your proposal in a feature branch. Please feel free to clone and test.
Example code:
````
Iterator iterator = surfer.iterator(read("sample.json"), "$.store.book[*]");
````

**Comment by wanglingsong** [comment]
@oleg-smith does this implementation meet your requirement?

**Comment by oleg-smith** [comment]
@wanglingsong Yes, it works perfectly. Thank you.
