### ISSUE TITLE
Parsing JSON object 

### ISSUE THREAD

**Issue by bjoerngam** [jsurfer/JsonSurfer#28]
I'm having the following JSON object:

 "features": [
>     {
>       "type": "Feature",
>       "properties": {
>         "@id": "node/643464022",
>         "historic": "memorial",
>         "image": "imagesource",
>         "memorial:addr": "address",
>         "memorial:text": "text",
>         "memorial:type": "type",
>         "memorial:website": "website",
>         "name": "First Lastname",
>         "network": "network",
>         "person:date_of_birth": "date_of_birth",
>         "pos": "A1",
>         "website": "website",
>         "@timestamp": "2015-06-15T20:39:33Z",
>         "@version": 10,
>         "@changeset": 31992980,
>         "@user": "tomtom100",
>         "@uid": 2616776
>       },
>       "geometry": {
>         "type": "Point",
>         "coordinates": [
>           6.9601819,
>           50.9455431
>         ]
>       },
>       "id": "node/643464022"
>     },

Now I wanne look in the whole JSON array after a specifc coordinates, by using jsonSurfer. But when I'm using the code snippet I'm getting a error.

    JsonSurfer jsonSurfer = JsonSurferGson.INSTANCE;
            jsonSurfer.configBuilder()
                    .bind("$.features[0].geometry[?(@.coordinates=='6.9601819,50.9455431')]", new JsonPathListener() {
                        @Override
                        public void onValue(Object value, ParsingContext context) {
                             System.out.println("Surfing: " +value);
                        }
                    })
                    .buildAndSurf(itemsJson);
    
            return null;

The error message is the following:

> E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
>                                                                                      Process: com.example.android.stolpersteinear, PID: 14459
>                                                                                      java.lang.RuntimeException: An error occurred while executing
> doInBackground()
>                                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:318)
>                                                                                          at
> java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>                                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>                                                                                          at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>                                                                                          at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>                                                                                          at java.lang.Thread.run(Thread.java:761)
>                                                                                       Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
>                                                                                          at
> org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:66)
>                                                                                          at org.antlr.v4.runtime.Parser.match(Parser.java:206)
>                                                                                          at
> org.jsfr.json.compiler.JsonPathParser.exprEqualStr(JsonPathParser.java:1070)
>                                                                                          at org.jsfr.json.compiler.JsonPathParser.expr(JsonPathParser.java:804)
>                                                                                          at
> org.jsfr.json.compiler.JsonPathParser.filter(JsonPathParser.java:726)
>                                                                                          at org.jsfr.json.compiler.JsonPathParser.path(JsonPathParser.java:262)
>                                                                                          at
> org.jsfr.json.compiler.JsonPathCompiler.compile(JsonPathCompiler.java:216)
>                                                                                          at
> org.jsfr.json.SurfingConfiguration$Builder.bind(SurfingConfiguration.java:131)
>                                                                                          at utils.JSONData.fetchJsonArray(JSONData.java:44)
>                                                                                          at utils.JSONLoader.loadInBackground(JSONLoader.java:34)
>                                                                                          at utils.JSONLoader.loadInBackground(JSONLoader.java:18)
>                                                                                          at
> android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
>                                                                                          at
> android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
>                                                                                          at
> android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
>                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:304)
>                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                                          at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
>                                                                                          at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
>                                                                                          at java.lang.Thread.run(Thread.java:761) 
>                                                                                       Caused by: org.antlr.v4.runtime.InputMismatchException
>                                                                                          at
> org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:61)
>                                                                                          at org.antlr.v4.runtime.Parser.match(Parser.java:206) 
>                                                                                          at
> org.jsfr.json.compiler.JsonPathParser.exprEqualStr(JsonPathParser.java:1070) 
>                                                                                          at
> org.jsfr.json.compiler.JsonPathParser.expr(JsonPathParser.java:804) 
>                                                                                          at
> org.jsfr.json.compiler.JsonPathParser.filter(JsonPathParser.java:726) 
>                                                                                          at
> org.jsfr.json.compiler.JsonPathParser.path(JsonPathParser.java:262) 
>                                                                                          at
> org.jsfr.json.compiler.JsonPathCompiler.compile(JsonPathCompiler.java:216) 
>                                                                                          at
> org.jsfr.json.SurfingConfiguration$Builder.bind(SurfingConfiguration.java:131) 
>                                                                                          at utils.JSONData.fetchJsonArray(JSONData.java:44) 
>                                                                                          at utils.JSONLoader.loadInBackground(JSONLoader.java:34) 
>                                                                                          at utils.JSONLoader.loadInBackground(JSONLoader.java:18) 
>                                                                                          at
> android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312) 
>                                                                                          at
> android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69) 
>                                                                                          at
> android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66) 
>                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:304) 
>                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
>                                                                                          at
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
>                                                                                          at
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
>                                                                                          at java.lang.Thread.run(Thread.java:761)

 

Something like that works perfectly: 

    JsonSurfer jsonSurfer = JsonSurferGson.INSTANCE;
            jsonSurfer.configBuilder()
                    .bind("$.features[0].geometry.coordinates]", new JsonPathListener() {
                        @Override
                        public void onValue(Object value, ParsingContext context) {
                             System.out.println("Surfing: " +value);
                        }
                    })
                    .buildAndSurf(itemsJson);
    
            return null;

Thanks,
Bjoern

**Comment by wanglingsong** [comment]
Hi Bjoern,

In current version, the filter can only compare string or number not a Json array in your example. I'm afraid you may have to implement the comparison yourself in the JsonPathListener.

But it does have a bug in parsing quoted string in that JsonPath filter. I will fix it later.

Regards,
Leo

**Comment by bjoerngam** [comment]
Hi Leo, 

thanks for your fast response. 

Cheers,
Bjoern
