### ISSUE TITLE
Negation in JSON filter 

### ISSUE THREAD

**Issue by gauravphoenix** [jsurfer/JsonSurfer#32]
Following JSON path fails- `$..book[?(!(@.price<10 && @.category=='fiction'))]` while it works fine on http://jsonpath.com/. 

Looking at the code seems like the JSON Path grammar (JsonPath.g4) doesn't have negation support. Are there plans for supporting it?

**Comment by wanglingsong** [comment]
There is no concrete plan for it yet because I'm a little bit busy on other project recently. But Pull Requests are always welcomed for improving JsonSurfer.
