### ISSUE TITLE
Gson parser should support lenient parsing

### ISSUE THREAD

**Issue by cmuchinsky** [jsurfer/JsonSurfer#42]
By default Gson's `JsonReader` class uses strict parsing which seems logical, however once you start trying parse real world json data you frequently run into the following:
```
MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line ...
```
It would be nice if the `JsonReader` used by `GsonParser` was lenient by default, or at least had a way to configure it for lenient parsing.

**Comment by wanglingsong** [comment]
Sure, I think I can add an interface for GsonParser to accept Gons's JsonReader, then you can construct whatever you want and pass it to GsonParser.

**Comment by wanglingsong** [comment]
@cmuchinsky I just submitted a fix which should solve your problem. Looking forward yo your response.

**Comment by cmuchinsky** [comment]
The fix worked for me, thanks!
