### ISSUE TITLE
SurfingContext class should be public

### ISSUE THREAD

**Issue by cmuchinsky** [jsurfer/JsonSurfer#43]
The `SurfingContext` class should be made public, otherwise its not possible to implement a custom `JsonParserAdapter` in any package other than `org.jsfr.json`

**Comment by wanglingsong** [comment]
What kind of JsonParserAdaper do you want to implement? Why not jsut do it in org.jsfr.json package

**Comment by cmuchinsky** [comment]
I was looking to prototype a workaround for issue 42 with an anonymous class but was unable to.
