### ISSUE TITLE
Keys containin a space cannot be parsed

### ISSUE THREAD

**Issue by amanzan** [jsurfer/JsonSurfer#47]
I have a json with some keys that contain spaces ("Image Player". "Phone Number"). There's a ParseCancellationException if I try to parse it:

MyApp.getJsonSurfer().collectOne(jsonAsString, "$.fields.Phone Number")

How to handle when keys have spaces?

Here's the sample json:

`{
  "id": "some_id",
  "fields": {
    "Email": "email@example.com",
    "Status": "Amateur",
    "Image player": [
      {
        "id": "some_other_id",
        "url": "https://www.google.es",
        "filename": "image.png",
        "size": 413642,
        "type": "image/png",
        "thumbnails": {
          "small": {
            "width": 36,
            "height": 36
          },
          "large": {
            "width": 500,
            "height": 500
          },
          "full": {
            "width": 500,
            "height": 500
          }
        }
      }
    ],
    "Phone Number": "666666666",
    "Name": "Player one",
    "Wins": [
      0
    ],
    "Standing": [
      "Eliminated"
    ]
  },
  "createdTime": "2018-06-28T22:32:47.000Z"
}`

**Comment by wanglingsong** [comment]
Try this:
$.fields["Phone Number"]

**Comment by amanzan** [comment]
That didn't work either, but after several tests, apparently this works:

MyApp.getJsonSurfer().collectOne(jsonAsString, "$.fields[\'Phone Number\']")

With the double quote I was still getting the ParseCancellationException. It would be better if the "." remains between "fields" and the start bracket, but I will try to make it work like this.

Thanks for the quick response!!
