### ISSUE TITLE
Allow regular expression matching in filter

### ISSUE THREAD

**Issue by mthaak** [jsurfer/JsonSurfer#48]
Some other JsonPath libraries allow this, like [Jayway JsonPath](https://github.com/json-path/JsonPath) using the `[?(@.name =~ /foo.*?/i)]` syntax.

**Comment by wanglingsong** [comment]
This will be a useful feature. But I don't have too much time to implement it. I can leave this issue open, see if any volunteer.

**Comment by wanglingsong** [comment]
#51
