### ISSUE TITLE
Can JsonSurfer be used over multiple input files with same structure ?

### ISSUE THREAD

**Issue by MITIN33** [jsurfer/JsonSurfer#52]
I wanted explorer if JsonSurfer can work on scanning over similar json structure distributed over multiple files ?

**Comment by wanglingsong** [comment]
You can scan them one by one

**Comment by MITIN33** [comment]
my use case is i have to do grouping of data inside files based on some logic and exported the json data. Does it support distributed processing , kind of map reduce ?

**Comment by wanglingsong** [comment]
JsonSurfer does not have such map-reduce function.
