### ISSUE TITLE
Regression in 1.5.0 

### ISSUE THREAD

**Issue by thierrylegrain** [jsurfer/JsonSurfer#54]
Hello,

In 1.4.3, I have a code working well like that :
surfer.configBuilder()
		.bind("$.header", (JsonPathListener) (final Object value, final ParsingContext context) -> {
		}).bind("$.data[?(@.device-type=='vmanage')]",
				(JsonPathListener) (final Object value, final ParsingContext context) -> {
				})
		.bind("$.data[?(@.device-type=='vsmart')]",
				(JsonPathListener) (final Object value, final ParsingContext context) -> {
				})
		.buildAndSurf(entity.getContent());
Now, in 1.5.0, only the first bind found data. No data for the second and third bind (we have data with version 1.4.3)
If you removed the third bind, the second bind has data.
From my point of view, you have an issue when you have several binding with a filter on same attribute.

**Comment by wanglingsong** [comment]
Could you provide the sample json as well?

**Comment by thierrylegrain** [comment]
I attached an example
[example.json.txt](https://github.com/jsurfer/JsonSurfer/files/3287031/example.json.txt)

**Comment by wanglingsong** [comment]
You are right. It is a bug! I'll try to fix it and add corresponding test case for it soon.

**Comment by thierrylegrain** [comment]
Hi Leo,

Thank you for this quick analysis and answer.

Regards,
Thierry.

**Comment by wanglingsong** [comment]
@thierrylegrain Hi, I just committed a fix. Sorry for the late update.

**Comment by thierrylegrain** [comment]
Hi Léo,

No problem. Thank you so much.

Regards,
Thierry.
