### ISSUE TITLE
Could CollectOneListner be made public now collectOne is deprecated? No simple replacement exists?

### ISSUE THREAD

**Issue by NielsUll** [jsurfer/JsonSurfer#74]
I need to extract one element from the beginning of a large json structure, and would like to abort parsing as soon as it is found.
The collectOne() looks like just the thing, but it is deprecated. 

The CollectOneListener is not public, so I have to clone that class in my own code?

**Comment by wanglingsong** [comment]
you can try the new API.
https://github.com/jsurfer/JsonSurfer#collect-value-by-jsonpath

**Comment by NielsUll** [comment]
But that will still parse the entire message? 
I tested this trying to read this:

`{ "key1": "value1", "key2": "value2", something which is definitly not valid json `


I can read value1 using collectOne(), but not used the new AP - it will try to parse everything.

**Comment by wanglingsong** [comment]
If you want to stop immediately on the first occurrence. this example may help:
https://github.com/jsurfer/JsonSurfer#stoppable-parsing

**Comment by NielsUll** [comment]
Thank you - I had apparently missed that.
